name: resampling_neural_afx
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - flax==0.10.2
      - matplotlib==3.9.0
      - pandas==2.2.2
      - pip-chill==1.0.3
      - rocket-fft==0.2.5




